#!/bin/bash

# System Information Script
# Session 3 - Shell Scripting Homework

# Storing the system details inside variables
current_date=$(date)
host_name=$(hostname)
user_name=$(whoami)

echo "=================================="
echo "      System Information"
echo "=================================="

echo "Current Date : $current_date"
echo "Hostname     : $host_name"
echo "Username     : $user_name"

echo ""
echo "---------- Disk Usage ----------"
df -h

echo ""
echo "---------- Running Processes (first 10) ----------"
ps aux | head -10

echo ""
echo "---------- User Input ----------"
read -p "Enter your name: " name
read -p "Enter your roll number: " roll_no
read -p "Enter a directory name to create: " dir_name

# Creating the directory and the log file
mkdir -p "$dir_name"
echo "Directory created: $dir_name"

touch "$dir_name/process.log"
echo "File created: $dir_name/process.log"

# Saving the running process details into the file using output redirection
ps aux > "$dir_name/process.log"
echo "Running process details saved in $dir_name/process.log"

echo ""
echo "Report generated by $name (Roll No: $roll_no) on $current_date"
